### ISSUE TITLE
Latest 2.0 tag is outdated

### ISSUE THREAD

**Issue by robinmanuelthiel** [Azure/azure-functions-docker#159]
When using `mcr.microsoft.com/azure-functions/dotnet:2.0`, the actual runtime version is `2.0.12180` instead of the latest one. When starting this image, the following output appears:

```bash
info: Host.Startup[0]
      Starting Host (HostId=774b10368756-2137340777, InstanceId=784bdf3d-ec8b-4a72-a789-67d8d82d5ae8, Version=2.0.12180.0, ProcessId=7, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
```

When using `mcr.microsoft.com/azure-functions/dotnet:2.0.12673`, the runtime version is correct and even newer (`2.0.12673.0`).

```bash
info: Host.Startup[401]
      Starting Host (HostId=6b4e79a90a9b-2137340777, InstanceId=1d99be59-ec8e-494b-916e-e5a0760939e4, Version=2.0.12673.0, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
```

**So the `2.0` tag is very outdated.**

According to the [documentation](https://hub.docker.com/_/microsoft-azure-functions-base), the `2.0` tag for `azure-functions/dotnet` for example should give me the *latest version* of the Azure Functions runtime!

![image](https://user-images.githubusercontent.com/5874465/67148926-62a4bd80-f2a5-11e9-9d12-974f16b4cd45.png)

**Comment by ahmelsayed** [comment]
The process for releasing the Windows bits (not a container) and docker containers for linux is not ideal today. We miss the updates on the linux side frequently, mainly because Windows release starts first and is sometimes retaken multiple times to address issues that pop up, and when that happens sometimes the release for linux falls off the radar of the person doing the release. I've updated the internal release process and hopefully that improves it. 

The docs on docker hub are also sort of outdated since we have more tags now, so I'll update that too.
