### ISSUE TITLE
PowerShell 7 Core Tools image needs .NET Core 3.1

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-docker#590]
https://github.com/Azure/azure-functions-docker/blob/924e883612bef24e8aab06744ad19d1dbb8de72c/host/4/bullseye/amd64/powershell/powershell7-core-tools.Dockerfile#L1

**Comment by CooperLink** [comment]
Writing a PR currently to resolve this bug for you.  I would just like to point out that powershell7-core-tools has not included dotnet3.1 in its dockerfile since its inception 5 months ago shown here : https://github.com/Azure/azure-functions-docker/blame/67875a429d6bd52b6970521986cc5caa469f4783/host/4/bullseye/amd64/powershell/powershell7-core-tools.Dockerfile

I have copied the mechanism that all other v4 Dockerfiles use to download dotnet3.1.  I will need a hand from someone to understand how to test if this resolves the bug for you.  Dotnet 3.1 should be available though.
