### ISSUE TITLE
TimerTrigger functions run across all instances

### ISSUE THREAD

**Issue by esimkowitz** [Azure/azure-functions-docker#635]
I am copying this issue from here where it has been open for 2 years: https://github.com/Azure/azure-functions-host/issues/6015

When running Azure Functions in dotnet-isolated:4 with .NET 6, I am seeing that all my instances of my timer-trigger functions are executing at every event, despite the [official documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#scale-out) mentioning that only one instance should run for each timer event. We have all instances of the function linked to the same storage account so they should be able to synchronize. Any ideas? Is this expected?

This is currently blocking my team as we cannot properly scale our instances with timer triggers without risking weird concurrency issues in our data store.

**Comment by balag0** [comment]
Just to clarify couple of things
> We have all instances of the function linked to the same storage account

Shouldn't this be the only possible configuration since all instances of a function app map to a single function app which can only be linked to a single storage account. Or are you referring to different slots on the same function app?

>I am seeing that all my instances of my timer-trigger functions are executing at every event

Are 2 different instances of the same function app running invocations concurrently or is it the case that a new invocation starts on a different instance than the one that ran the previous invocation.

**Comment by esimkowitz** [comment]
To clarify, we use Kubernetes to host our Azure Functions so when I say instance of the function app, I am referring to separate pods running the same function app container with the same storage account.

**Comment by balag0** [comment]
Okay, hosted on kubernetes is a good clarification. 
Looks like this is already being tracked by https://github.com/Azure/azure-functions-host/issues/6015
So lets close this to avoid duplication and the host repo is the right place anyway.
