### ISSUE TITLE
Deletion of issue 843

### ISSUE THREAD

**Issue by mseiler90** [Azure/azure-functions-docker#853]
[REMOVED SENSITIVE INFORMATION]

**Comment by fabiocav** [comment]
@mseiler90 / @vachillo-msft sharing the update here for clarity.

The issue was indeed intentionally deleted following the security disclosure guidelines. We did collect all the information you shared and the issues are being actively worked on, so no context was lost. We were informed by our support group that they were in communication with you/your team and sharing this information, including the action to delete the issue, so looks like there was a gap in communication.

The security policy, including guidance on how to report security issues is available [here](https://github.com/Azure/azure-functions-docker/security/policy).

Redacting instead of deleting this time to make sure you have the details, but will remove the information above. As mentioned, this is being addressed and we've captured what you've shared here and with our support group.

Thank you!

**Comment by fabiocav** [comment]
@mseiler90 closing this, but please let us know if you have any questions/concerns.

Thank you again!

**Comment by mseiler90** [comment]
Thank you for the update. Our company is one of the largest companies in the country and therefore as you may expect communication amongst an application team (like the team I am on) is not always aware of communications that our enterprise security team has. I am not on the security team and was not aware at the time of any such communication about deleting the issue. I do now understand your preferred approach for security vulnerability reporting after reviewing the linked file, but I would suggest that if that approach is preferred that it be included in the README or that there be an issue template which includes this explanation. I would have never noticed this otherwise. Perhaps others that are a bit more diligent in digging through files would notice it. 

Regardless, I appreciate the follow up on this. Thank you
